=== ivandoslic/otvoreni-recepti/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://or.fer.unizg.hr/otvorenirecepti.json",
    "type": "array",
    "title": "Otvoreni Recepti",
    "description": "Skup recepata za otvoreno računarstvo.",
    "items": {
        "type": "object",
        "title": "Recept",
        "required": [
            "id_recepta",
            "naziv_recepta",
            "opis_recepta",
            "recept_youtube_url",
            "koraci_recepta",
            "recept_wiki_url",
            "vrijeme_pripreme",
            "vrijeme_kuhanja",
            "broj_porcija",
            "tezina",
            "drzava",
            "sastojci"
        ],
        "properties": {
            "id_recepta": {
                "type": "integer",
                "title": "ID recepta",
                "description": "Jedinstveni identifikator recepta."
            },
            "naziv_recepta": {
                "type": "string",
                "title": "Naziv recepta",
                "description": "Naziv jela za koji je recept."
            },
            "opis_recepta": {
                "type": "string",
                "title": "Opis recepta",
                "description": "Detaljan opis recepta."
            },
            "recept_youtube_url": {
                "type": "string",
                "title": "YouTube URL recepta",
                "description": "YouTube poveznica na videozapis pripreme recepta."
            },
            "koraci_recepta": {
                "type": "string",
                "title": "Koraci pripreme recepta",
                "description": "Detaljan popis koraka za pripremu recepta."
            },
            "recept_wiki_url": {
                "type": [
                    "string",
                    "null"
                ],
                "title": "Wikipedia URL recepta",
                "description": "Poveznica na Wikipedia stranicu o receptu, ako postoji."
            },
            "vrijeme_pripreme": {
                "type": "string",
                "title": "Vrijeme pripreme",
                "description": "Vrijeme potrebno za pripremu sastojaka (u minutama)."
            },
            "vrijeme_kuhanja": {
                "type": "string",
                "title": "Vrijeme kuhanja",
                "description": "Vrijeme potrebno za kuhanje (u minutama)."
            },
            "broj_porcija": {
                "type": "integer",
                "title": "Broj porcija",
                "description": "Broj porcija koje recept omogućuje."
            },
            "tezina": {
                "type": "string",
                "title": "Težina pripreme",
                "description": "Razina težine pripreme recepta (npr. lako, srednje, teško)."
            },
            "drzava": {
                "type": "object",
                "title": "Država podrijetla",
                "description": "Informacije o državi iz koje recept potječe.",
                "properties": {
                    "drzava_id": {
                        "type": "integer",
                        "title": "ID države",
                        "description": "Jedinstveni identifikator države."
                    },
                    "naziv_drzave": {
                        "type": "string",
                        "title": "Naziv države",
                        "description": "Ime države podrijetla recepta."
                    },
                    "glavni_grad": {
                        "type": "string",
                        "title": "Glavni grad",
                        "description": "Glavni grad države podrijetla recepta."
                    },
                    "zastava_url": {
                        "type": "string",
                        "title": "URL zastave",
                        "description": "Poveznica na sliku zastave države."
                    },
                    "regija": {
                        "type": "string",
                        "title": "Regija",
                        "description": "Regija države podrijetla recepta."
                    }
                }
            },
            "sastojci": {
                "type": "array",
                "title": "Popis sastojaka",
                "description": "Popis svih sastojaka potrebnih za recept.",
                "items": {
                    "type": "object",
                    "title": "Sastojak",
                    "required": [
                        "naziv_sastojka",
                        "kolicina",
                        "mjerna_jedinica"
                    ],
                    "properties": {
                        "naziv_sastojka": {
                            "type": "string",
                            "title": "Naziv sastojka",
                            "description": "Ime sastojka potrebnog za recept."
                        },
                        "kolicina": {
                            "type": "number",
                            "title": "Količina sastojka",
                            "description": "Količina potrebna za određeni sastojak."
                        },
                        "mjerna_jedinica": {
                            "type": "string",
                            "title": "Mjerna jedinica",
                            "description": "Mjerna jedinica za količinu sastojka (npr. grami, mililitri)."
                        }
                    }
                }
            }
        }
    }
}

=== ivandoslic/otvoreni-recepti/recipes.json
[
  {
    "id_recepta": 1,
    "naziv_recepta": "Pašticada",
    "opis_recepta": "Tradicionalno jelo od goveđeg mesa u bogatom umaku, najčešće posluženo s domaćim njokima.",
    "recept_youtube_url": "https://youtu.be/XAE1C4bC9IE?si=yV25H16s-deEe2zB",
    "koraci_recepta": "Meso se marinira preko noći, zatim se polako kuha u umaku od vina, začina i povrća.",
    "recept_wiki_url": "https://hr.wikipedia.org/wiki/Pa%C5%A1ticada",
    "vrijeme_pripreme": "02:00:00",
    "vrijeme_kuhanja": "03:00:00",
    "broj_porcija": 6,
    "tezina": "Srednje",
    "drzava": {
      "drzava_id": 6,
      "naziv_drzave": "Hrvatska",
      "glavni_grad": "Zagreb",
      "zastava_url": "https://flagsapi.com/HR/flat/64.png",
      "regija": "Jugoistočna Europa"
    },
    "sastojci": [
      {
        "naziv_sastojka": "Goveđi but",
        "kolicina": 1.6,
        "mjerna_jedinica": "kg"
      },
      {
        "naziv_sastojka": "Suha slanina",
        "kolicina": 0.15,
        "mjerna_jedinica": "kg"
      },
      { "naziv_sastojka": "Mast", "kolicina": 0.15, "mjerna_jedinica": "kg" },
      { "naziv_sastojka": "Ulje", "kolicina": 0.15, "mjerna_jedinica": "l" },
      { "naziv_sastojka": "Mrkva", "kolicina": 0.4, "mjerna_jedinica": "kg" },
      { "naziv_sastojka": "Celer", "kolicina": 0.1, "mjerna_jedinica": "kg" },
      {
        "naziv_sastojka": "Korijen peršina",
        "kolicina": 0.1,
        "mjerna_jedinica": "kg"
      },
      { "naziv_sastojka": "Luk", "kolicina": 2.0, "mjerna_jedinica": "kom" },
      {
        "naziv_sastojka": "Češnjak",
        "kolicina": 5.0,
        "mjerna_jedinica": "češnja"
      },
      {
        "naziv_sastojka": "Korijander u zrnu",
        "kolicina": 1.0,
        "mjerna_jedinica": "žličica"
      }
    ]
  },
  {
    "id_recepta": 2,
    "naziv_recepta": "Sarma",
    "opis_recepta": "Listovi kiselog kupusa punjeni mljevenim mesom i rižom, kuhani u bogatom umaku.",
    "recept_youtube_url": "https://youtu.be/SGswt_asbzE?si=FtTVa9Y_umo-6RSP",
    "koraci_recepta": "Listove kiselog kupusa napuniti smjesom mesa i riže, zamotati i kuhati na laganoj vatri nekoliko sati.",
    "recept_wiki_url": "https://hr.wikipedia.org/wiki/Sarma",
    "vrijeme_pripreme": "00:30:00",
    "vrijeme_kuhanja": "02:00:00",
    "broj_porcija": 6,
    "tezina": "Srednje",
    "drzava": {
      "drzava_id": 6,
      "naziv_drzave": "Hrvatska",
      "glavni_grad": "Zagreb",
      "zastava_url": "https://flagsapi.com/HR/flat/64.png",
      "regija": "Jugoistočna Europa"
    },
    "sastojci": [
      {
        "naziv_sastojka": "Fant za punjenu papriku i sarmu",
        "kolicina": 1.0,
        "mjerna_jedinica": "paket"
      },
      {
        "naziv_sastojka": "Mljeveno meso",
        "kolicina": 0.6,
        "mjerna_jedinica": "kg"
      },
      { "naziv_sastojka": "Riža", "kolicina": 0.07, "mjerna_jedinica": "kg" },
      {
        "naziv_sastojka": "Kiseli kupus",
        "kolicina": 1.0,
        "mjerna_jedinica": "glava"
      },
      {
        "naziv_sastojka": "Panceta",
        "kolicina": 6.0,
        "mjerna_jedinica": "ploška"
      },
      { "naziv_sastojka": "Passata", "kolicina": 0.15, "mjerna_jedinica": "l" },
      {
        "naziv_sastojka": "Dimljena paprika",
        "kolicina": 1.0,
        "mjerna_jedinica": "žličica"
      },
      {
        "naziv_sastojka": "Vegeta",
        "kolicina": 1.0,
        "mjerna_jedinica": "žličica"
      }
    ]
  },
  {
    "id_recepta": 3,
    "naziv_recepta": "Čobanac",
    "opis_recepta": "Spicy gulaš od raznih vrsta mesa s paprikom i začinima, tradicionalno pripreman na otvorenoj vatri.",
    "recept_youtube_url": "https://youtu.be/_jWkjbgh9QY?si=Uqt4Ddl92fNUbF-A",
    "koraci_recepta": "Razne vrste mesa izrezati i kuhati sa začinima i paprikom, dodati krumpir po želji.",
    "recept_wiki_url": null,
    "vrijeme_pripreme": "00:30:00",
    "vrijeme_kuhanja": "02:30:00",
    "broj_porcija": 8,
    "tezina": "Teško",
    "drzava": {
      "drzava_id": 6,
      "naziv_drzave": "Hrvatska",
      "glavni_grad": "Zagreb",
      "zastava_url": "https://flagsapi.com/HR/flat/64.png",
      "regija": "Jugoistočna Europa"
    },
    "sastojci": [
      {
        "naziv_sastojka": "Fant mješavina za slavonski čobanac - ljuti",
        "kolicina": 1.0,
        "mjerna_jedinica": "paket"
      },
      { "naziv_sastojka": "Voda", "kolicina": 2.0, "mjerna_jedinica": "l" },
      {
        "naziv_sastojka": "Svinjetina",
        "kolicina": 0.4,
        "mjerna_jedinica": "kg"
      },
      {
        "naziv_sastojka": "Junetina",
        "kolicina": 0.4,
        "mjerna_jedinica": "kg"
      },
      { "naziv_sastojka": "Lovor", "kolicina": 1.0, "mjerna_jedinica": "list" },
      {
        "naziv_sastojka": "Crvena paprika",
        "kolicina": 2.0,
        "mjerna_jedinica": "kom"
      },
      {
        "naziv_sastojka": "Bijelo vino",
        "kolicina": 0.1,
        "mjerna_jedinica": "l"
      }
    ]
  },
  {
    "id_recepta": 4,
    "naziv_recepta": "Fuži s tartufima",
    "opis_recepta": "Tradicionalna istarska tjestenina s umakom od tartufa.",
    "recept_youtube_url": "https://www.youtube.com/watch?v=R0ehjlAgGwU",
    "koraci_recepta": "Skuhati fuže, pripremiti umak od tartufa i poslužiti.",
    "recept_wiki_url": "https://hr.wikipedia.org/wiki/Fu%C5%BEi",
    "vrijeme_pripreme": "00:15:00",
    "vrijeme_kuhanja": "00:15:00",
    "broj_porcija": 4,
    "tezina": "Jednostavno",
    "drzava": {
      "drzava_id": 6,
      "naziv_drzave": "Hrvatska",
      "glavni_grad": "Zagreb",
      "zastava_url": "https://flagsapi.com/HR/flat/64.png",
      "regija": "Jugoistočna Europa"
    },
    "sastojci": [
      {
        "naziv_sastojka": "Pšenično oštro brašno",
        "kolicina": 0.4,
        "mjerna_jedinica": "kg"
      },
      { "naziv_sastojka": "Jaja", "kolicina": 2.0, "mjerna_jedinica": "kom" },
      { "naziv_sastojka": "Ulje", "kolicina": 1.0, "mjerna_jedinica": "žlica" },
      {
        "naziv_sastojka": "Bijelo vino",
        "kolicina": 2.0,
        "mjerna_jedinica": "žlice"
      },
      { "naziv_sastojka": "Sol", "kolicina": 1.0, "mjerna_jedinica": "žlica" },
      { "naziv_sastojka": "Maslac", "kolicina": 0.1, "mjerna_jedinica": "kg" },
      {
        "naziv_sastojka": "Tartufi",
        "kolicina": 0.05,
        "mjerna_jedinica": "kg"
      },
      {
        "naziv_sastojka": "Peršin",
        "kolicina": 1.0,
        "mjerna_jedinica": "žlica"
      },
      {
        "naziv_sastojka": "Vegeta Maestro crni papar mljeveni",
        "kolicina": 0.5,
        "mjerna_jedinica": "žličica"
      }
    ]
  },
  {
    "id_recepta": 5,
    "naziv_recepta": "Peka",
    "opis_recepta": "Jelo pripremljeno ispod peke s mesom i povrćem, polako kuhano u vlastitom soku.",
    "recept_youtube_url": "https://www.youtube.com/watch?v=_AuZrBuZBC4",
    "koraci_recepta": "Pripremiti meso i povrće, peći ispod peke s krumpirom i začinima.",
    "recept_wiki_url": "https://hr.wikipedia.org/wiki/Peka",
    "vrijeme_pripreme": "00:20:00",
    "vrijeme_kuhanja": "03:00:00",
    "broj_porcija": 6,
    "tezina": "Teško",
    "drzava": {
      "drzava_id": 6,
      "naziv_drzave": "Hrvatska",
      "glavni_grad": "Zagreb",
      "zastava_url": "https://flagsapi.com/HR/flat/64.png",
      "regija": "Jugoistočna Europa"
    },
    "sastojci": [
      {
        "naziv_sastojka": "Svinjetina",
        "kolicina": 4.0,
        "mjerna_jedinica": "kom"
      },
      { "naziv_sastojka": "Luk", "kolicina": 2.0, "mjerna_jedinica": "kom" },
      {
        "naziv_sastojka": "Patlidžan",
        "kolicina": 2.0,
        "mjerna_jedinica": "kom"
      },
      {
        "naziv_sastojka": "Tikvica",
        "kolicina": 2.0,
        "mjerna_jedinica": "kom"
      },
      {
        "naziv_sastojka": "Crvena paprika",
        "kolicina": 2.0,
        "mjerna_jedinica": "kom"
      },
      {
        "naziv_sastojka": "Žuta paprika",
        "kolicina": 2.0,
        "mjerna_jedinica": "kom"
      },
      {
        "naziv_sastojka": "Krumpir",
        "kolicina": 7.0,
        "mjerna_jedinica": "kom"
      },
      {
        "naziv_sastojka": "Češnjak",
        "kolicina": 3.0,
        "mjerna_jedinica": "češnja"
      },
      {
        "naziv_sastojka": "Gljive",
        "kolicina": 1.0,
        "mjerna_jedinica": "paket"
      },
      {
        "naziv_sastojka": "Maslinovo ulje",
        "kolicina": 3.0,
        "mjerna_jedinica": "dl"
      }
    ]
  },
  {
    "id_recepta": 6,
    "naziv_recepta": "Brudet",
    "opis_recepta": "Dalmatinski riblji paprikaš od raznih vrsta ribe, kuhano s vinom, lukom i rajčicama.",
    "recept_youtube_url": "https://www.youtube.com/watch?v=0riEEGi-VyE",
    "koraci_recepta": "Razne vrste ribe kuhati s lukom, rajčicama, vinom i začinima.",
    "recept_wiki_url": "https://hr.wikipedia.org/wiki/Brodet",
    "vrijeme_pripreme": "00:20:00",
    "vrijeme_kuhanja": "01:00:00",
    "broj_porcija": 4,
    "tezina": "Srednje",
    "drzava": {
      "drzava_id": 6,
      "naziv_drzave": "Hrvatska",
      "glavni_grad": "Zagreb",
      "zastava_url": "https://flagsapi.com/HR/flat/64.png",
      "regija": "Jugoistočna Europa"
    },
    "sastojci": [
      { "naziv_sastojka": "Riba", "kolicina": 0.5, "mjerna_jedinica": "kg" },
      { "naziv_sastojka": "Luk", "kolicina": 1.0, "mjerna_jedinica": "kom" },
      {
        "naziv_sastojka": "Češnjak",
        "kolicina": 3.0,
        "mjerna_jedinica": "češnja"
      },
      {
        "naziv_sastojka": "Peršin",
        "kolicina": 2.0,
        "mjerna_jedinica": "žlice"
      },
      {
        "naziv_sastojka": "Čili papričica",
        "kolicina": 0.5,
        "mjerna_jedinica": "kom"
      },
      {
        "naziv_sastojka": "Kapari",
        "kolicina": 1.0,
        "mjerna_jedinica": "žlica"
      },
      {
        "naziv_sastojka": "Masline",
        "kolicina": 6.0,
        "mjerna_jedinica": "kom"
      },
      {
        "naziv_sastojka": "Crno vino",
        "kolicina": 0.5,
